### ISSUE TITLE
virtualbox-host-dkms 6.1.18-1 fails to compile

### ISSUE THREAD

**Issue by mabod** [xanmod/linux#125] opened 2021-02-08 10:38 UTC
With latest 5.10.14-xanmod1-cacule-1-cacule virtualbox dkms modules do not compile. Other 5.10.14 kernels do not have that issue:

```
vboxhost, 6.1.18_OSE, 5.10.14-arch1-1, x86_64: installed
vboxhost, 6.1.18_OSE, 5.10.14-zen1-1-zen, x86_64: installed
```
This is on Arch linux. 

virtualbox dkms error log for 5.10.14-xanmod1-cacule:
```
make: Entering directory '/usr/lib/modules/5.10.14-xanmod1-cacule-1-cacule/build'
  CC [M]  /var/lib/dkms/vboxhost/6.1.18_OSE/build/vboxnetflt/linux/VBoxNetFlt-linux.o
  CC [M]  /var/lib/dkms/vboxhost/6.1.18_OSE/build/vboxnetflt/VBoxNetFlt.o
  CC [M]  /var/lib/dkms/vboxhost/6.1.18_OSE/build/vboxnetflt/SUPR0IdcClient.o
  CC [M]  /var/lib/dkms/vboxhost/6.1.18_OSE/build/vboxnetadp/linux/VBoxNetAdp-linux.o
  CC [M]  /var/lib/dkms/vboxhost/6.1.18_OSE/build/vboxnetflt/SUPR0IdcClientComponent.o
  CC [M]  /var/lib/dkms/vboxhost/6.1.18_OSE/build/vboxnetadp/VBoxNetAdp.o
  CC [M]  /var/lib/dkms/vboxhost/6.1.18_OSE/build/vboxnetflt/linux/SUPR0IdcClient-linux.o
  CC [M]  /var/lib/dkms/vboxhost/6.1.18_OSE/build/vboxdrv/linux/SUPDrv-linux.o
  CC [M]  /var/lib/dkms/vboxhost/6.1.18_OSE/build/vboxdrv/SUPDrv.o
  CC [M]  /var/lib/dkms/vboxhost/6.1.18_OSE/build/vboxdrv/SUPDrvGip.o
  CC [M]  /var/lib/dkms/vboxhost/6.1.18_OSE/build/vboxdrv/SUPDrvSem.o
  CC [M]  /var/lib/dkms/vboxhost/6.1.18_OSE/build/vboxdrv/SUPDrvTracer.o
  CC [M]  /var/lib/dkms/vboxhost/6.1.18_OSE/build/vboxdrv/SUPLibAll.o
  CC [M]  /var/lib/dkms/vboxhost/6.1.18_OSE/build/vboxdrv/r0drv/alloc-r0drv.o
  CC [M]  /var/lib/dkms/vboxhost/6.1.18_OSE/build/vboxdrv/r0drv/initterm-r0drv.o
  CC [M]  /var/lib/dkms/vboxhost/6.1.18_OSE/build/vboxdrv/r0drv/memobj-r0drv.o
  CC [M]  /var/lib/dkms/vboxhost/6.1.18_OSE/build/vboxdrv/r0drv/mpnotification-r0drv.o
  CC [M]  /var/lib/dkms/vboxhost/6.1.18_OSE/build/vboxdrv/r0drv/powernotification-r0drv.o
  CC [M]  /var/lib/dkms/vboxhost/6.1.18_OSE/build/vboxdrv/r0drv/linux/assert-r0drv-linux.o
  CC [M]  /var/lib/dkms/vboxhost/6.1.18_OSE/build/vboxdrv/r0drv/linux/alloc-r0drv-linux.o
  CC [M]  /var/lib/dkms/vboxhost/6.1.18_OSE/build/vboxdrv/r0drv/linux/initterm-r0drv-linux.o
  CC [M]  /var/lib/dkms/vboxhost/6.1.18_OSE/build/vboxdrv/r0drv/linux/memobj-r0drv-linux.o
  CC [M]  /var/lib/dkms/vboxhost/6.1.18_OSE/build/vboxdrv/r0drv/linux/memuserkernel-r0drv-linux.o
  CC [M]  /var/lib/dkms/vboxhost/6.1.18_OSE/build/vboxdrv/r0drv/linux/mp-r0drv-linux.o
  CC [M]  /var/lib/dkms/vboxhost/6.1.18_OSE/build/vboxdrv/r0drv/linux/mpnotification-r0drv-linux.o
  CC [M]  /var/lib/dkms/vboxhost/6.1.18_OSE/build/vboxdrv/r0drv/linux/process-r0drv-linux.o
  CC [M]  /var/lib/dkms/vboxhost/6.1.18_OSE/build/vboxdrv/r0drv/linux/rtStrFormatKernelAddress-r0drv-linux.o
  CC [M]  /var/lib/dkms/vboxhost/6.1.18_OSE/build/vboxdrv/r0drv/linux/semevent-r0drv-linux.o
  CC [M]  /var/lib/dkms/vboxhost/6.1.18_OSE/build/vboxdrv/r0drv/linux/semeventmulti-r0drv-linux.o
  CC [M]  /var/lib/dkms/vboxhost/6.1.18_OSE/build/vboxdrv/r0drv/linux/semfastmutex-r0drv-linux.o
  CC [M]  /var/lib/dkms/vboxhost/6.1.18_OSE/build/vboxdrv/r0drv/linux/semmutex-r0drv-linux.o
  CC [M]  /var/lib/dkms/vboxhost/6.1.18_OSE/build/vboxdrv/r0drv/linux/spinlock-r0drv-linux.o
/var/lib/dkms/vboxhost/6.1.18_OSE/build/vboxdrv/SUPDrvTracer.o: warning: objtool: .text+0x7: indirect jump found in RETPOLINE build
/var/lib/dkms/vboxhost/6.1.18_OSE/build/vboxdrv/SUPDrvTracer.o: warning: objtool: supdrvTracerProbeFireStub() is missing an ELF size annotation
/var/lib/dkms/vboxhost/6.1.18_OSE/build/vboxdrv/SUPDrvTracer.o: warning: objtool: missing symbol for insn at offset 0x0

make[2]: *** [scripts/Makefile.build:279: /var/lib/dkms/vboxhost/6.1.18_OSE/build/vboxdrv/SUPDrvTracer.o] Error 255
make[2]: *** Deleting file '/var/lib/dkms/vboxhost/6.1.18_OSE/build/vboxdrv/SUPDrvTracer.o'
make[2]: *** Waiting for unfinished jobs....
/var/lib/dkms/vboxhost/6.1.18_OSE/build/vboxdrv/r0drv/linux/memuserkernel-r0drv-linux.o: warning: objtool: VBoxHost_RTR0MemKernelCopyTo()+0xa: redundant CLD
/var/lib/dkms/vboxhost/6.1.18_OSE/build/vboxdrv/r0drv/linux/memuserkernel-r0drv-linux.o: warning: objtool: VBoxHost_RTR0MemKernelCopyFrom()+0xa: redundant CLD
  LD [M]  /var/lib/dkms/vboxhost/6.1.18_OSE/build/vboxnetadp/vboxnetadp.o
  LD [M]  /var/lib/dkms/vboxhost/6.1.18_OSE/build/vboxnetflt/vboxnetflt.o
make[1]: *** [scripts/Makefile.build:496: /var/lib/dkms/vboxhost/6.1.18_OSE/build/vboxdrv] Error 2
make: *** [Makefile:1808: /var/lib/dkms/vboxhost/6.1.18_OSE/build] Error 2
make: Leaving directory '/usr/lib/modules/5.10.14-xanmod1-cacule-1-cacule/build'
```

**Comment by mabod** [comment] 2021-02-09 09:04
The issue is related to the latest binutils update to 2.36-3. Downgrading to 2.35.1-1 solves the compilation error.

Something in the xanmod kernel config is incompatible with the new binutils.

**Comment by figue** [comment] 2021-02-09 09:42
I can confirm this issue. But it seems odd. What changes between 2.35 and 2.36?

**Comment by figue** [comment] 2021-02-09 10:00
Also a diff between stock branch and cacule branch is minimum:

```
figue on pluto /tmp ➜  diff -u config_stock config_cacule
--- config_stock	2021-02-09 10:57:39.331653753 +0100
+++ config_cacule	2021-02-09 10:58:28.713655320 +0100
@@ -160,6 +160,7 @@
 CONFIG_UCLAMP_BUCKETS_COUNT=5
 # end of Scheduler features
 
+CONFIG_CACULE_SCHED=y
 CONFIG_ARCH_SUPPORTS_NUMA_BALANCING=y
 CONFIG_ARCH_WANT_BATCHED_UNMAP_TLB_FLUSH=y
 CONFIG_CC_HAS_INT128=y
@@ -199,7 +200,7 @@
 CONFIG_NET_NS=y
 CONFIG_CHECKPOINT_RESTORE=y
 CONFIG_SCHED_AUTOGROUP=y
-CONFIG_SCHED_AUTOGROUP_DEFAULT_ENABLED=y
+# CONFIG_SCHED_AUTOGROUP_DEFAULT_ENABLED is not set
 # CONFIG_SYSFS_DEPRECATED is not set
 CONFIG_RELAY=y
 CONFIG_BLK_DEV_INITRD=y
 ```

**Comment by mabod** [comment] 2021-02-09 11:06
Your diff looks really small. When I compare with stock arch config the diff is much bigger. It has 5208 lines. I will not post it here.

**Comment by mabod** [comment] 2021-02-09 11:17
By the way, just to clarify, `linux-xanmod 5.10.14-1` has the same issue.
This is not just about the cacule version.

**Comment by figue** [comment] 2021-02-09 13:30
Excuse me... I though that linux-xanmod was fine and cacule was not :(

It seems that is with some custom kernels, not only xanmod. So let's look around if someone figure out.

**Comment by xanmod** [comment] 2021-02-09 15:00
Note: virtualbox 6.1.18 dkms is compiling ok with 5.10.14-xanmod1 on ubuntu / debian.

**Comment by mabod** [comment] 2021-02-09 17:06
@xanmod: This is because Ubuntu / Debian are not coming with binutils 2.36. Both come with older version. But only binutils 2.36 triggers the issue in combination with the xanmod kernel. Other kernels in combination with bintuils 2.36 and virtualbox do not have that issue.

**Comment by TechXero** [comment] 2021-02-09 17:24
I am having same issue on Arch. I will skip XanMod for now until issue resolved...

**Comment by mabod** [comment] 2021-02-10 20:51
Somebody reported this issue upstream to virtualbox:

https://www.virtualbox.org/ticket/20178

**Comment by TechXero** [comment] 2021-02-10 23:01
So outside remains with 5.10.15?

**Comment by H1K0USEN** [comment] 2021-02-16 12:29
Now here on 5.11 it seems to fail even with binutils downgraded 2.35.

**Comment by TechXero** [comment] 2021-02-16 12:37
Works fine here with downgraded binutils, also vBox update just released

```
(1/8) Creating system user accounts...
(2/8) Reloading system manager configuration...
(3/8) Reloading device manager configuration...
(4/8) Arming ConditionNeedsUpdate...
(5/8) Install DKMS modules
==> dkms install --no-depmod -m vboxhost -v 6.1.18_OSE -k 5.10.16-arch1-1
==> dkms install --no-depmod -m vboxhost -v 6.1.18_OSE -k 5.11.0-xanmod1-1
==> depmod 5.11.0-xanmod1-1
==> depmod 5.10.16-arch1-1
(6/8) Updating icon theme caches...
(7/8) Updating the desktop file MIME type cache...
(8/8) Updating the MIME type database...
```

**Comment by mabod** [comment] 2021-02-16 13:03
> Now here on 5.11 it seems to fail even with binutils downgraded 2.35.

I found the solution in some other forum:

edit /usr/src/vboxhost-6.1.18_OSE/vboxnetflt/linux/VBoxNetFlt-linux.c
and add

#include <linux/ethtool.h>

directly after

#include <linux/netdevice.h>

This is line #41 in my case

**Comment by TechXero** [comment] 2021-02-16 13:09
I updated vBox and binutils so far so good no more issues. Did not have to edit anything...

Will report back in case issue reappears...

**Comment by figue** [comment] 2021-02-16 13:52
Works for me as well. Hope Virtualbox release soon the official patch. Closing this issue.

**Closed by figue** 2021-02-16 13:52 UTC

**Comment by mabod** [comment] 2021-02-26 15:08
The initial issue is still open. Virtualbox do not build with xanmod and binutils 2.36. 
patching the virtualbox source as mentioned in my earlier comment (https://github.com/xanmod/linux/issues/125#issuecomment-779822943) is solving a different issue which occurs even with binutils 2.35

The intially reported incompatibility between xanmod/virtualbox and binutils 2.35 persists.

**Comment by figue** [comment] 2021-02-26 17:48
@mabod yes, I know. I think until upstream fix the main issue, we have to patch and use binutils 2.35.

**Comment by jarrard** [comment] 2021-03-08 12:20
This issue still happens for me with manjaro spin of xanmod. Who knows when it will be fixed in latest binutils.

```
/var/lib/dkms/vboxhost/6.1.18_OSE/build/vboxdrv/SUPDrvTracer.o: warning: objtool: .text+0x7: indirect jump found in RETPOLINE build
/var/lib/dkms/vboxhost/6.1.18_OSE/build/vboxdrv/SUPDrvTracer.o: warning: objtool: supdrvTracerProbeFireStub() is missing an ELF size annotation
/var/lib/dkms/vboxhost/6.1.18_OSE/build/vboxdrv/SUPDrvTracer.o: warning: objtool: missing symbol for insn at offset 0x0
make[2]: *** [scripts/Makefile.build:279: /var/lib/dkms/vboxhost/6.1.18_OSE/build/vboxdrv/SUPDrvTracer.o] Error 255
make[2]: *** Deleting file '/var/lib/dkms/vboxhost/6.1.18_OSE/build/vboxdrv/SUPDrvTracer.o'
make[2]: *** Waiting for unfinished jobs....
/var/lib/dkms/vboxhost/6.1.18_OSE/build/vboxdrv/r0drv/linux/memuserkernel-r0drv-linux.o: warning: objtool: VBoxHost_RTR0MemKernelCopyTo()+0xa: redundant CLD
/var/lib/dkms/vboxhost/6.1.18_OSE/build/vboxdrv/r0drv/linux/memuserkernel-r0drv-linux.o: warning: objtool: VBoxHost_RTR0MemKernelCopyFrom()+0xa: redundant CLD
  LD [M]  /var/lib/dkms/vboxhost/6.1.18_OSE/build/vboxnetflt/vboxnetflt.o
make[1]: *** [scripts/Makefile.build:496: /var/lib/dkms/vboxhost/6.1.18_OSE/build/vboxdrv] Error 2
make: *** [Makefile:1803: /var/lib/dkms/vboxhost/6.1.18_OSE/build] Error 2
```

**Comment by aviallon** [comment] 2021-03-26 12:09
From [https://www.virtualbox.org/ticket/20178#comment:1](https://www.virtualbox.org/ticket/20178#comment:1) :
```diff
--- vboxdrv/SUPDrvTracer.c    2020-02-20 14:23:59.000000000 +0100
+++ vboxdrv/SUPDrvTracer.c    2021-03-19 08:44:27.953262434 +0100
@@ -1479,6 +1479,10 @@
 # if   defined(RT_ARCH_AMD64)
 __asm__(" \
             movq    g_pfnSupdrvProbeFireKernel(%rip), %rax                  \n\
+999:\n\
+            .pushsection .discard.retpoline_safe\n\
+            .quad 999b\n\
+            .popsection\n\
             jmp     *%rax \n\
 ");
 # elif defined(RT_ARCH_X86)
```
