### ISSUE TITLE
Mac address Table issue

### ISSUE THREAD

**Issue by TJ101** [xanmod/linux#120] opened 2021-01-30 16:07 UTC
Dear All,

I’m still having a serious issue with the ARP table on my router where MAC addresses are suddenly disappearing causing devices such as switches and servers connected to interfaces on the router to become unreachable.

I’m tried putting in static arp entries to see if this will fix the issue and will report back.

Here is an example of such an entry
 arp –I lan –s 192.168.1.1 a0:36:9f:04:32:bc

It’s obviously far from ideal. 

There are no errors in the kernel, syslog or message logs.

This has only happened since I upgraded from a Debian 4.19 kernel to the Xanmod 5.10.11.

Does anyone know how I can further diagnose this issue?

Are there some kernel options affecting the MAC table between versions?

I’ve set the following in /etc/sysctl.d/90-override.conf
net.ipv4.neigh.default.gc_thresh1=1024
net.ipv4.neigh.default.gc_thresh2=4096
net.ipv4.neigh.default.gc_thresh3=16384

I’ve carried out all the normal checks like looking for a layer 2 loop but as I said, this issue does not occur with the 4.19 kernel and happens intermittently on the 5.10.11 kernel?

I’m wondering if it is a driver issue for the Intel igb based network cards?

Any inputs are most gratefully received.

**Comment by xanmod** [comment] 2021-01-30 17:41
Investigating, this problem seems to be related to the iptables 1.8.2 version of debian buster.Can you upgrade to 1.8.5 from the buster-backports repository?

**Comment by xanmod** [comment] 2021-01-30 17:42
Investigating, this problem seems to be related to the iptables 1.8.2 version of debian buster.

Can you upgrade to 1.8.5 from the buster-backports repository?

**Comment by TJ101** [comment] 2021-01-31 01:02
I've upgraded to iptables 1.8.5 from backports as requested.

Can you share more information about the issue you have found with iptables 1.8.2.

Many Thanks,

**Comment by xanmod** [comment] 2021-01-31 01:39
There have been changes in security and kernel networking syscalls. Iptables 1.8.2 is an outdated version for the current Linux.

I have already added a note on the frontpage suggesting to buster users to enable backports repo.

If the issue is resolved, close it.

**Comment by TJ101** [comment] 2021-01-31 02:40
Thanks for this.

I’ve currently only updated iptables from buster-backports.

Should I update anything else?

Do you think it safe to do a full update from buster-backports rather than being selective and only updating particular packages?

I’ll let you know how I get on and if the issue is resolved, I will close the ticket.

**Comment by xanmod** [comment] 2021-01-31 03:04
Backport packages are still tested by debian maintainers.

Usually for users who want or need a more updated system.

Partially updating packages can cause dependency problems, so it is more recommended to use the repository.

**Comment by TJ101** [comment] 2021-02-01 02:26
Unfortunately, the suggested fix doesn’t appear to have worked.

I updated my apt sources with the buster-backports repository and ran the following to upgrade iptables to version 1.8.5.

apt-get install iptables/buster-backports

This installed the latest version of iptables in buster backports and its dependencies.

However, the same issue has come back.  A host directly connected to an interface on the router suddenly became unreachable. 
 
The host was directly connected to the interface via a vlan i.e.  eth0.555

When I looked at the ARP table for the interface, the IP address of the remote host was there because it was being requested.

But the HWaddress (MAC) showed (incomplete).

A reboot was the only way to bring back the host with a MAC address entry in the ARP table. I tried taking the interface down and bringing it up first. But this didn't work. 

I’ve had to switch back to a Debian 4.19 kernel to keep everything stable.

Interestingly, I also found that I was also unable to ping the interfaces own assigned IPv4 IP address.
 
It’s almost like IPv4 stopped working ☹ 

I tried apt-get and it was only connecting over IPv6 addresses.
 
Which is really strange as I have precedence ::ffff:0:0/96  100 set in the /etc/gai.conf

Any ideas how to further diagnose this issue?

**Comment by xanmod** [comment] 2021-02-01 16:38
Does the kernel 5.9.15-1 from backports work well?

**Comment by TJ101** [comment] 2021-02-01 23:26
I previously only used the following backports kernel 5.3.0-0.bpo.2-amd64 and had no issues.

I’ve just installed linux-xanmod-lts (5.4.94-xanmod1) and will test with this.

I’ve kept the testing environment the same and only updated iptables and it’s dependencies using the following syntax.

apt-get install iptables/buster-backports

After looking at the following:-
https://wiki.archlinux.org/index.php/MAC_address_spoofing#iproute2
https://git.kernel.org/pub/scm/network/iproute2/iproute2.git

I am wondering if it would be a good idea to update iproute2 as well.

Currently Debian Buster uses iproute2 version 4.20.0-2 which is over two years old.

In buster-backports the version is now 5.9.0-1

If I type the following:-

apt-get -t buster-backports dist-upgrade

The following packages are available for upgrade using the buster-backports repository.

"bind9-host dirmngr dnsutils e2fslibs e2fsprogs e2fsprogs-l10n exim4 exim4-base exim4-config exim4-daemon-light firmware-amd-graphics firmware-linux firmware-linux-nonfree  firmware-misc-nonfree geoip-database gnupg gnupg-l10n gnupg-utils gnupg2 gpg gpg-agent gpg-wks-client gpg-wks-server gpgconf gpgsm gpgv hplip hplip-data intel-microcode iproute2 less libatk1.0-0 libatk1.0-data libcom-err2 libcryptsetup12 libext2fs2 libgeoip1 libhpmud0 libiptc0 libldap-2.4-2 libldap-common liblouis-data libnss-systemd libpam-systemd libpcap0.8 libsane-hpaio libseccomp2 libss2 libsystemd0 libudev1 libunbound8 libzstd1 linux-compiler-gcc-8-x86 linux-image-amd64 linux-libc-dev manpages manpages-dev mutt nftables openssh-client openssh-server openssh-sftp-server printer-driver-hpcups printer-driver-hpijs printer-driver-postscript-hp python3-debianbts python3-idna systemd systemd-sysv udev"

To me iproute2 looks like the only other package that might cause an issue with MAC addresses on interfaces. What do you think?

I’m obviously trying to find the exact cause of the issue, so I don’t think it’s a good idea to just update everything from buster-backports at this stage.

I’ll test and see what I find.

**Comment by xanmod** [comment] 2021-02-02 00:37
You can update iproute2 without any dependency / conflicts problems, in the xanmod repository it has version 5.8.0 to support fq_pie qdisc.

**Comment by TJ101** [comment] 2021-02-02 14:20
Thanks, 

I’m going to wait and see if I can reproduce the same issue with the Xanmod 5.4.94 LTS kernel.  

If I do, I will then upgrade iproute2 to see if this helps.

It looks like fq_pie was added to iproute2 on the 04-02-20.

https://git.kernel.org/pub/scm/network/iproute2/iproute2.git/commit/?id=9dced637f8dd269e0a409eb2eec1404d54d517f4

The Debian backports version is 5.9.0-1 which is newer than the Xanmod version of 5.8.0.

Have you patched anything in the Xanmod version of iproute2? Would it not be better to use the newest version from Debian backports?

The latest version from git is 5.10. I guess it matches the kernel version? Perhaps we should all be using this version?

https://git.kernel.org/pub/scm/network/iproute2/iproute2.git/tag/?h=v5.10.0

Can you add this version to your repository for testing please?

**Comment by TJ101** [comment] 2021-02-04 22:29
The Xanmod 5.4.94 LTS kernel seems to work fine.

I’ve not had any issues with MAC addresses disappearing.

I would say the issue I have is caused by outdated core networking packages even though I am using Buster-backports.

As 5.10 is the latest kernel code base, I would say it is probably a good idea to compile and include the following networking related packages in the Xanmod repository from git source.

Iptables-nft (iptables alternative which is the default in Debian Buster)

Iproute2 (needs to be the 5.10 branch to match the kernel version or the latest code)

Please see the following article https://lwn.net/Articles/828370/

I think this will provide better support and network performance on all Debian and Ubuntu builds using the latest 5.10 Xanmod kernels.

**Comment by TJ101** [comment] 2021-02-20 04:11
I’ve been doing lots of real-world testing and think I have found another issue with the new kernel config when using Xanmod 5.11 on a router.

In this thread there are a couple of issues which have contributed to various connectivity problems.

Firstly, the MAC address problems have been fixed by upgrading iptables using buster-backports and iproute2 using the latest iproute2 version provided by Xanmod.

However, I’ve still had issues with forwarded packets getting dropped or delayed when traffic increases on my test router.

So, I decided to check what changes there are between the 4.19 Debian Buster and 5.11 Xanmod kernels and how they might affect network performance. 

When looking at the config, I decided to focus on Interrupts as I previously had a problem when MSIX was not working correctly on a network card and this caused connectivity issues when traffic got above 2 Gbps on a 10 Gbps Link.

I found the following differences.

HZ 250 -> 500 The Frequency has been increased. Which provides a more responsive kernel but can reduce throughput.
 HZ_250 y -> n
 NO_HZ_FULL n -> y ** This enables a full tickless Kernel.
 NO_HZ_IDLE y -> n ** This disables tickless operation at idle
+HZ_500 y
+RCU_FAST_NO_HZ n ** This option disables RCU grace periods. Which is good because when enabled it increases real-time latency. 

It turns out that it is not recommended to enable Tickless operation when a CPU has a  high work load or has lots of short bursts of CPU usage. As the overhead from switching to and from idle and transitioning between user and kernel execution is high and increases latency.

Please see the following: -
https://www.kernel.org/doc/Documentation/timers/NO_HZ.txt

More importantly kernels can not predict when a packet will arrive at a network card. Therefore, networking requires the use of interrupt handlers and deferrable functions.

https://www.oreilly.com/library/view/understanding-the-linux/0596002130/ch18s04.html

A tickless kernel is an operating system kernel in which timer interrupts do not occur at regular intervals, but are only delivered as required. There is therefore a lag from idle and I believe this is causing networking performance issues.

Here is a useful report on the challenges of  using a tickless kernel with hardware.

https://www.researchgate.net/publication/266866770_Getting_maximum_mileage_out_of_tickless

From what I have found, a tickless kernel only slightly reduces power usage on most systems. 

I am wondering if it is really a benefit?

**Closed** 2022-01-17 21:51 UTC
